// components/NavBar.vue
<template>
  <div
    class="w-full h-12 flex-shrink-0 px-6 flex flex-wrap items-center justify-between bg-black"
  >
    <div>
      <span class="text-white font-extrabold text-3xl">Game of Life</span>
    </div>
    <div id="controls" class="h-full my-auto py-1 text-xl">
      <minimal-button>{{ gridState }}</minimal-button>
      <minimal-button @click="setGridState('PAUSE')" v-if="gridState === 'PLAY'"
        >Pause</minimal-button
      >
      <minimal-button @click="setGridState('PLAY')" v-else>
        Play
      </minimal-button>
      <minimal-button @click="setGridState('RANDOM')">Randomize</minimal-button>
      <minimal-button @click="setGridState('EDIT')">Edit</minimal-button>
      <minimal-button @click="setGridState('CLEAR')">Clear</minimal-button>
    </div>
  </div>
</template>

<script>
import { mapGetters } from 'vuex'
import MinimalButton from '../components/MinimalButton.vue'

export default {
  components: {
    MinimalButton
  },
  computed: mapGetters({
    gridState: 'gridControlState/get'
  }),
  methods: {
    setGridState(newGridState) {
      this.$store.commit('gridControlState/set', newGridState)
    }
  }
}
</script>

// src/NavBar.tsx
import React from "react";
import SlowDown from "./static/SlowDown.svg";
import Play from "./static/Play.svg";
import Faster from "./static/Faster.svg";
import Randomize from "./static/Randomize.svg";
import Pause from "./static/Pause.svg";
import Edit from "./static/Edit.svg";

const controlClassname = "h-full -mt-10 ml-8 inline-block";

const NavBar: React.FC = () => {
	return (
		<div className="flex items-center justify-between flex-wrap h-20 bg-black px-6 py-1 text-white font-extrabold text-5xl">
			<div>
				<span>Game of Life</span>
			</div>
			<div id="controls" className="h-10">
				<img className={controlClassname} src={SlowDown} alt=""/>
				<img className={controlClassname} src={Play} alt=""/>
				<img className={controlClassname} src={Faster} alt=""/>
				<img className={controlClassname} src={Randomize} alt=""/>
				<img className={controlClassname} src={Pause} alt=""/>
				<img className={controlClassname} src={Edit} alt=""/>
			</div>
		</div>
	);
};

export default NavBar;
